### ISSUE TITLE
Implement CI workflow to provide page preview within a PR

### ISSUE THREAD

**Issue by negin513** [NCAR/HPC-Docs#23]
The page preview for every PR would be specially practical for the PR review.

Essential Components:
* On-the-Fly Preview: Our workflow should be able to generate a real-time preview of the page(s) modified in a PR.
* Accessible Linking: The link to the preview should be shared in the PR comments so that reviewers and contributors can easily check it out. (The idea behind this comes from project Pythia cookbook templates where PRs preview are linked in a comment. 

<img width="1182" alt="Screenshot 2023-10-13 at 1 03 58 PM" src="https://github.com/NCAR/HPC-Docs/assets/17344536/68f62e5c-a5a2-430d-a537-1c12b0b7320a">

Thanks to @mtrahan41 who implemented readthedocs preview for each PR which should be visible from the PR links.

**Comment by negin513** [comment]
@mtrahan41, I think this is complete with your rtd implementations but I just want to check with you. If you think this is complete I will mark this issue as closed. Thanks!

**Comment by mtrahan41** [comment]
Agreed I like the solution we came up with! Thanks!
