### ISSUE TITLE
Links to examples of Large Allocation Request broken

### ISSUE THREAD

**Issue by DominikStiller** [NCAR/HPC-Docs#241]
The two links to examples of a Large Allocation Request are broken, or at least unavailable to me, even when logged into the KB with my CIT account:
https://github.com/NCAR/HPC-Docs/blob/5da1a1fac51248c1d083542859f900ccb80854e1/docs/allocations/university-allocations/university-large-allocation-request-preparation-instructions.md?plain=1#L33

This is somewhat related to #179.

The deadline for Large Allocation Requests is coming up on Sept. 10, so it would be nice to have this fixed before.

**Comment by DominikStiller** [comment]
The inaccessible documents are also linked on another page: https://github.com/NCAR/HPC-Docs/blob/main/docs/allocations/determining-computational-resource-needs.md?plain=1#L220-L222

**Comment by dphow** [comment]
Thanks Dominik for reporting this. I will see if I can find these original proposal examples and get these fixed.

**Comment by benkirk** [comment]
I've recovered the sources just now and am working a fix @dphow - yes thank you for the report!
