### ISSUE TITLE
Repository Lincense

### ISSUE THREAD

**Issue by negin513** [NCAR/HPC-Docs#6]
I think the repository needs license but I am not sure what license we should choose for this. 

I think maybe Apache or CC licenses are used a lot for docs and tutorials. 

Here is the license for NERSC: https://gitlab.com/NERSC/nersc.gitlab.io/-/blob/main/LICENSE?ref_type=heads

Also, adding DOI will be beneficial for future metrics and reports but that is another discussion.

**Comment by negin513** [comment]
Considering @vanderwb comment, I think maybe we should choose Apache 2.0 license, since the vision is that outside collaborators can also add to our documentations. 

But I am wondering what others think about this? @benkirk @mtrahan41 any thoughts?

Thanks @vanderwb for providing this email.

**Comment by benkirk** [comment]
I'm considering https://creativecommons.org/licenses/by-sa/4.0/, with OK from Legal.
This is "Share Alike with Attribution", and no restrictions for commercial vs. non-
commercial derived works.

This particular license:

- Share — copy and redistribute the material in any medium or format for any purpose, even commercially.

- Adapt — remix, transform, and build upon the material for any purpose, even commercially. The licensor cannot revoke these freedoms as long as you follow the license terms.

Provided that:

 - Attribution - You must give [appropriate credit ](https://creativecommons.org/licenses/by-sa/4.0/#), provide a link to the license, and [indicate if changes were made ](https://creativecommons.org/licenses/by-sa/4.0/#). You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

 - ShareAlike - If you remix, transform, or build upon the material, you must distribute your contributions under the [same license ](https://creativecommons.org/licenses/by-sa/4.0/#)as the original.

- No additional restrictions - You may not apply legal terms or [technological measures ](https://creativecommons.org/licenses/by-sa/4.0/#)that legally restrict others from doing anything the license permits.
